# GpuDetect.ps1
#
# Hardware detection/gating layer for the #118 harness, built to be
# injectable and testable rather than scattering "if simulate" checks
# throughout the main script.
#
# IMPORTANT SEPARATION OF CONCERNS:
#   - Get-PhysicalGpuInfo NEVER lies. It always reports what Python/
#     PyTorch/nvidia-smi actually see on THIS machine: real torch.version
#     .cuda, real installed package versions, real torch.cuda.get_arch_list(),
#     real torch.cuda execution results, real physical GPU identity, real
#     compute capability.
#   - Get-SimulationConfig / Get-EffectiveTargetRequirement produce a
#     SEPARATE "target requirement" object used ONLY by this harness's own
#     gating logic (e.g. "should we treat this run as targeting Blackwell
#     hardware and proceed with the cu128 experiment?"). It never touches,
#     patches, or overrides anything torch itself reports.
#   - Every report generated by the main script prints PHYSICAL_* and
#     SIMULATED_* fields side by side, never merged, so the two can never
#     be confused for one another.

Set-StrictMode -Version Latest

$script:BlackwellMinCapabilityMajor = 12

function Get-PhysicalGpuInfo {
    <#
        .SYNOPSIS
        Queries the REAL physical GPU/CUDA/torch state via the target
        venv's python interpreter. Never faked, never overridden.
    #>
    param(
        [Parameter(Mandatory = $true)][string]$PythonPath,
        [Parameter(Mandatory = $true)][string]$ProbeScriptPath
    )

    $native = Invoke-NativeProcess -FilePath $PythonPath -ArgumentList @($ProbeScriptPath)

    $info = [PSCustomObject]@{
        Native              = $native
        Ok                  = $false
        PythonVersion       = $null
        TorchVersion        = $null
        TorchVersionCuda    = $null
        CudaAvailable       = $false
        DeviceName          = $null
        ComputeCapability   = $null
        ArchList            = @()
        TorchvisionVersion  = $null
        TorchaudioVersion   = $null
        RawJson             = $null
        ParseError          = $null
    }

    if (-not $native.Success) {
        $info.ParseError = "probe process did not exit 0 (exit=$($native.ExitCode))"
        return $info
    }

    try {
        $parsed = $native.StdOut | ConvertFrom-Json
    }
    catch {
        $info.ParseError = "failed to parse probe JSON: $($_.Exception.Message)"
        return $info
    }

    $info.RawJson = $native.StdOut
    if ($parsed.PSObject.Properties.Name -contains 'python_version') { $info.PythonVersion = $parsed.python_version }
    if ($parsed.PSObject.Properties.Name -contains 'torch_version') { $info.TorchVersion = $parsed.torch_version }
    if ($parsed.PSObject.Properties.Name -contains 'torch_version_cuda') { $info.TorchVersionCuda = $parsed.torch_version_cuda }
    if ($parsed.PSObject.Properties.Name -contains 'cuda_available') { $info.CudaAvailable = [bool]$parsed.cuda_available }
    if ($parsed.PSObject.Properties.Name -contains 'device_name') { $info.DeviceName = $parsed.device_name }
    if ($parsed.PSObject.Properties.Name -contains 'device_capability') { $info.ComputeCapability = $parsed.device_capability }
    if ($parsed.PSObject.Properties.Name -contains 'arch_list') { $info.ArchList = @($parsed.arch_list) }
    if ($parsed.PSObject.Properties.Name -contains 'torchvision_version') { $info.TorchvisionVersion = $parsed.torchvision_version }
    if ($parsed.PSObject.Properties.Name -contains 'torchaudio_version') { $info.TorchaudioVersion = $parsed.torchaudio_version }
    if ($parsed.PSObject.Properties.Name -contains 'torch_import_error') { $info.ParseError = "torch import failed: $($parsed.torch_import_error)" }

    $info.Ok = ($null -eq $info.ParseError)
    return $info
}

function Get-SimulationConfig {
    <#
        .SYNOPSIS
        Determines whether development-only Blackwell simulation is
        active. Opt-in requires BOTH the -SimulateBlackwell switch AND an
        explicit, verbosely-named environment variable acknowledgement, so
        it can never activate by accident (a stray switch, a copy-pasted
        command, or a default value cannot turn this on by itself).
    #>
    param(
        [bool]$SimulateSwitch = $false
    )

    $ackVar = 'STEMWERK_RTX50_DEV_SIMULATION_ACK'
    $requiredAckValue = 'I-UNDERSTAND-THIS-IS-NOT-REAL-BLACKWELL-HARDWARE'
    $ackValue = [System.Environment]::GetEnvironmentVariable($ackVar)

    $active = $false
    $reason = ''
    if ($SimulateSwitch -and ($ackValue -eq $requiredAckValue)) {
        $active = $true
        $reason = 'switch + environment acknowledgement both present'
    }
    elseif ($SimulateSwitch -and ($ackValue -ne $requiredAckValue)) {
        $active = $false
        $reason = "switch present but $ackVar not set to required acknowledgement value; simulation NOT activated (fail closed)"
    }
    elseif (-not $SimulateSwitch -and ($ackValue -eq $requiredAckValue)) {
        $active = $false
        $reason = "$ackVar set but -SimulateBlackwell switch not passed; simulation NOT activated (fail closed)"
    }
    else {
        $active = $false
        $reason = 'simulation not requested'
    }

    return [PSCustomObject]@{
        Active            = $active
        Reason            = $reason
        SimulatedGpuName  = 'NVIDIA GeForce RTX 5070'
        SimulatedCapability = '12.0'
        AckVariableName   = $ackVar
    }
}

function Get-EffectiveTargetRequirement {
    <#
        .SYNOPSIS
        Returns the capability/name this run's gating decisions should be
        evaluated against: the simulated Blackwell identity in dev
        simulation mode, otherwise the real physical GPU identity.
        This value is used ONLY for harness gating decisions, never
        reported as if it were physical hardware.
    #>
    param(
        [Parameter(Mandatory = $true)]$SimulationConfig,
        [Parameter(Mandatory = $true)]$PhysicalInfo
    )

    if ($SimulationConfig.Active) {
        return [PSCustomObject]@{
            Simulated         = $true
            GpuName           = $SimulationConfig.SimulatedGpuName
            ComputeCapability = $SimulationConfig.SimulatedCapability
        }
    }

    return [PSCustomObject]@{
        Simulated         = $false
        GpuName           = $PhysicalInfo.DeviceName
        ComputeCapability = $PhysicalInfo.ComputeCapability
    }
}

function Test-IsBlackwellCapability {
    <#
        .SYNOPSIS
        Pure function: does the given "major.minor" capability string
        represent Blackwell-generation (sm_120 / compute capability 12.x)
        hardware?
    #>
    param(
        [string]$ComputeCapability
    )
    if ([string]::IsNullOrWhiteSpace($ComputeCapability)) { return $false }
    $parts = $ComputeCapability.Split('.')
    if ($parts.Length -lt 1) { return $false }
    $major = 0
    if (-not [int]::TryParse($parts[0], [ref]$major)) { return $false }
    return ($major -ge $script:BlackwellMinCapabilityMajor)
}

function Test-ArchListSupportsCapability {
    <#
        .SYNOPSIS
        Honestly checks whether a torch build's real, reported
        get_arch_list() output contains an sm_XX entry for the given
        "major.minor" capability. No faking: this reads exactly what the
        installed build advertises.
    #>
    param(
        [string[]]$ArchList,
        [string]$ComputeCapability
    )
    if ([string]::IsNullOrWhiteSpace($ComputeCapability)) { return $false }
    $parts = $ComputeCapability.Split('.')
    if ($parts.Length -lt 2) { return $false }
    $target = "sm_$($parts[0])$($parts[1])"
    return ($ArchList -contains $target)
}
