# GpuDetect.ps1
#
# Hardware detection/gating layer for the #118 harness, built to be
# injectable and testable rather than scattering "if simulate" checks
# throughout the main script.
#
# IMPORTANT SEPARATION OF CONCERNS:
#   - Get-PhysicalGpuInfo NEVER lies. It always reports what Python/
#     PyTorch/nvidia-smi actually see on THIS machine: real torch.version
#     .cuda, real installed package versions, real torch.cuda.get_arch_list(),
#     real torch.cuda execution results, real physical GPU identity, real
#     compute capability.
#   - A simulated target (a plain {GpuName;ComputeCapability} object) is
#     used ONLY by this harness's own gating logic (e.g. "should we treat
#     this run as targeting Blackwell hardware and proceed with the cu128
#     experiment?"). It never touches, patches, or overrides anything
#     torch itself reports. As of v2, the ONLY code that can ever
#     construct one lives in dev\STEMwerk-RTX50-cu128-test-SIMULATED.ps1
#     (excluded from the tester ZIP) - this file and the public tester
#     path contain no simulation-activation logic at all.
#   - Every report generated by the main script prints PHYSICAL_* and
#     SIMULATED_* fields side by side, never merged, so the two can never
#     be confused for one another.

Set-StrictMode -Version Latest

$script:BlackwellMinCapabilityMajor = 12

function Get-PhysicalGpuInfo {
    <#
        .SYNOPSIS
        Queries the REAL physical GPU/CUDA/torch state via the target
        venv's python interpreter. Never faked, never overridden.
    #>
    param(
        [Parameter(Mandatory = $true)][string]$PythonPath,
        [Parameter(Mandatory = $true)][string]$ProbeScriptPath
    )

    $native = Invoke-NativeProcess -FilePath $PythonPath -ArgumentList @($ProbeScriptPath)

    $info = [PSCustomObject]@{
        Native              = $native
        Ok                  = $false
        PythonVersion       = $null
        TorchVersion        = $null
        TorchVersionCuda    = $null
        CudaAvailable       = $false
        DeviceName          = $null
        ComputeCapability   = $null
        ArchList            = @()
        TorchvisionVersion  = $null
        TorchaudioVersion   = $null
        RawJson             = $null
        ParseError          = $null
    }

    if (-not $native.Success) {
        $info.ParseError = "probe process did not exit 0 (exit=$($native.ExitCode))"
        return $info
    }

    try {
        $parsed = $native.StdOut | ConvertFrom-Json
    }
    catch {
        $info.ParseError = "failed to parse probe JSON: $($_.Exception.Message)"
        return $info
    }

    $info.RawJson = $native.StdOut
    if ($parsed.PSObject.Properties.Name -contains 'python_version') { $info.PythonVersion = $parsed.python_version }
    if ($parsed.PSObject.Properties.Name -contains 'torch_version') { $info.TorchVersion = $parsed.torch_version }
    if ($parsed.PSObject.Properties.Name -contains 'torch_version_cuda') { $info.TorchVersionCuda = $parsed.torch_version_cuda }
    if ($parsed.PSObject.Properties.Name -contains 'cuda_available') { $info.CudaAvailable = [bool]$parsed.cuda_available }
    if ($parsed.PSObject.Properties.Name -contains 'device_name') { $info.DeviceName = $parsed.device_name }
    if ($parsed.PSObject.Properties.Name -contains 'device_capability') { $info.ComputeCapability = $parsed.device_capability }
    if ($parsed.PSObject.Properties.Name -contains 'arch_list') { $info.ArchList = @($parsed.arch_list) }
    if ($parsed.PSObject.Properties.Name -contains 'torchvision_version') { $info.TorchvisionVersion = $parsed.torchvision_version }
    if ($parsed.PSObject.Properties.Name -contains 'torchaudio_version') { $info.TorchaudioVersion = $parsed.torchaudio_version }
    if ($parsed.PSObject.Properties.Name -contains 'torch_import_error') { $info.ParseError = "torch import failed: $($parsed.torch_import_error)" }

    $info.Ok = ($null -eq $info.ParseError)
    return $info
}

function Test-IsBlackwellCapability {
    <#
        .SYNOPSIS
        Pure function: does the given "major.minor" capability string
        represent Blackwell-generation (sm_120 / compute capability 12.x)
        hardware?
    #>
    param(
        [string]$ComputeCapability
    )
    if ([string]::IsNullOrWhiteSpace($ComputeCapability)) { return $false }
    $parts = $ComputeCapability.Split('.')
    if ($parts.Length -lt 1) { return $false }
    $major = 0
    if (-not [int]::TryParse($parts[0], [ref]$major)) { return $false }
    return ($major -ge $script:BlackwellMinCapabilityMajor)
}

function Test-ArchListSupportsCapability {
    <#
        .SYNOPSIS
        Honestly checks whether a torch build's real, reported
        get_arch_list() output contains an sm_XX entry for the given
        "major.minor" capability. No faking: this reads exactly what the
        installed build advertises.
    #>
    param(
        [string[]]$ArchList,
        [string]$ComputeCapability
    )
    if ([string]::IsNullOrWhiteSpace($ComputeCapability)) { return $false }
    $parts = $ComputeCapability.Split('.')
    if ($parts.Length -lt 2) { return $false }
    $target = "sm_$($parts[0])$($parts[1])"
    return ($ArchList -contains $target)
}
